spring.application.name=document-portal
spring.datasource.url=jdbc:mysql://localhost:3306/docportal
spring.datasource.username=root
spring.datasource.password=Anku864@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=docportal_secret_key_2024_make_this_long
jwt.expiration=86400000