#spring.application.name=document-portal
#spring.datasource.url=jdbc:mysql://localhost:3306/docportal
#spring.datasource.username=root
#spring.datasource.password=Anku864@
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#jwt.secret=docportal_secret_key_2024_make_this_long
#jwt.expiration=86400000


spring.application.name=document-portal
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/docportal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Anku864@}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
jwt.secret=${JWT_SECRET:docportal_secret_key_2024_make_this_long}
jwt.expiration=${JWT_EXPIRATION:86400000}
server.port=${PORT:8080}